web/router.ex
defmodule Blognix.Router do
  use Blognix.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
  end

  pipeline :api do
    plug :accepts, ["json"]
  end


  scope "/", Blognix do
    pipe_through :browser # Use the default browser stack

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete

    get "/registration", RegistrationController, :new
    post "/registration", RegistrationController, :create

    resources "/blogs", BlogsController

    get "/", BlogsController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", Blognix do
  #   pipe_through :api
  # end
end

lib/blognix/endpoint.ex
defmodule Blognix.Endpoint do
  use Phoenix.Endpoint, otp_app: :blognix

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :blognix, gzip: false,
    only: ~w(css images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_blognix_key",
    signing_salt: "m0x9dOQZ"

  plug :router, Blognix.Router
end

lib/blognix/password.ex
defmodule Blognix.Password do
  alias Phitter.Repo
  import Ecto.Changeset, only: [put_change: 3]
  import Comeonin.Bcrypt, only: [hashpwsalt: 1]

  @doc """
    Generates a password for the user changeset and stores it to the
    changeset as encrypted_password
  """

  def generate_password(changeset) do
    put_change(changeset, :encrypted_password,
    hashpwsalt(changeset.params["password"]))
  end

  @doc """
    Generates the password for the changeset and then stores it to the database
  """

  def generate_password_and_store(changeset) do
    changeset
      |> generate_password
      |> Repo.insert
  end
end

lib/blognix/repo.ex
defmodule Blognix.Repo do
  use Ecto.Repo, otp_app: :blognix
end

lib/blognix/slugify.ex
defmodule Blognix.Slugify do
  import Inflex
  alias Phitter.Repo
  import Ecto.Changeset, only: [put_change: 3]

  def generate_slug(changeset) do
    put_change(changeset, :slug, parameterize(changeset.params["title"]))
  end
end

web/models/blog.ex
defmodule Blognix.Blog do
  use Blognix.Web, :model
  alias Blognix.Repo

  schema "blogs" do
    field :slug, :string
    field :title, :string
    field :description, :string
    belongs_to :user, Blognix.User

    timestamps
  end

  @required_fields ~w(title description user_id)
  @optional_fields ~w()

  before_insert Blognix.Slugify, :generate_slug

  @doc """
  Creates a changeset based on the `model` and `params`.

  If `params` are nil, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> validate_unique(:title, on: Repo, downcase: true)
  end
end

web/models/user.ex
defmodule Blognix.User do
  use Blognix.Web, :model
  alias Blognix.Repo

  schema "users" do
    field :username, :string
    field :email, :string
    field :encrypted_password, :string
    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true
    has_one :blog, Blognix.Blog

    timestamps
  end

  @required_fields ~w(username email password password_confirmation)
  @optional_fields ~w()
  @email_regex ~r/^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i

  before_insert Blognix.Password, :generate_password

  @doc """
  Creates a changeset based on the `model` and `params`.

  If `params` are nil, an invalid changeset is returned
  with no validation performed.
  """


  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> validate_unique(:username, on: Repo, downcase: true)
    |> validate_unique(:email, on: Repo, downcase: true)
    |> validate_format(:email, @email_regex)
    |> validate_length(:password, min: 8)
    |> validate_length(:password_confirmation, min: 8)
    |> validate_confirmation(:password)
  end

end

web/controllers/blogs_controller.ex
defmodule Blognix.BlogsController do
  use Blognix.Web, :controller
  alias Blognix.Repo
  alias Blognix.Blog

  plug Blognix.Plug.Authenticate when not action in [:index, :show]
  plug :scrub_params, "blog" when action in [:create, :update]
  plug :action

  def new(conn, _) do
    changeset = Blog.changeset(%Blog{})
    render conn, changeset: changeset
  end

  def create(conn, %{"blog" => blog_params}) do
    new_blog = build(conn.assigns.current_user, :blog)
    changeset = Blog.changeset(new_blog, blog_params)
    if changeset.valid? do
      blog = Repo.insert(changeset)

      conn
        |> put_flash(:info, "Successfully created your blog!")
        |> redirect(to: blogs_path(conn, :show, blog.slug))
    else
      render conn, "new.html", changeset: changeset
    end
  end

  def index(conn, _) do
    render conn
  end

  def show(conn, %{"id" => slug}) do
    blog = Repo.get_by(Blog, slug: slug)
    if blog do
      render conn, blog: blog
    else
      conn
        |> put_status(:not_found)
        |> render(Blognix.ErrorView, "404.html")
    end
  end

  def show(conn, _) do
    if conn.assigns[:subdomain] do
      blog = Repo.get_by(Blog, slug: conn.assigns.subdomain)
      if blog do
        render conn, blog: blog
      else
        conn
          |> put_status(:not_found)
          |> render(Blognix.ErrorView, "404.html")
      end
    else
      conn
        |>redirect(to: blogs_path(conn, :index))
    end
  end
end

web/controllers/registration_controller.ex
defmodule Blognix.RegistrationController do
  use Blognix.Web, :controller
  alias Blognix.Repo

  plug :action

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render conn, changeset: changeset
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.changeset(%User{}, user_params)
    if changeset.valid? do
      new_user = Repo.insert(changeset)

      conn
        |> put_flash(:info, "Successfully registered and logged in")
        |> put_session(:current_user, new_user)
        |> redirect(to: "/")
    else
      render conn, "new.html", changeset: changeset
    end
  end
end

web/controllers/session_controller.ex
defmodule Blognix.SessionController do
  use Blognix.Web, :controller

  plug :scrub_params, "user" when action in [:create]
  plug :action

  def new(conn, _params) do
    render conn, changeset: User.changeset(%User{})
  end

  def create(conn, %{"user" => user_params}) do
    user = if is_nil(user_params["email"]) do
      nil
    else
      Repo.get_by(User, email: user_params["email"])
    end

    user
      |> sign_in(user_params["password"], conn)
  end

  def delete(conn, _) do
    delete_session(conn, :current_user)
      |> put_flash(:info, "You have been logged out")
      |> redirect(to: session_path(conn, :new))
  end

  defp sign_in(user, _, conn) when is_nil(user) do
    conn
      |> put_flash(:error, "Username or password are incorrect.")
      |> render "new.html", changeset: User.changeset(%User{})
  end

  defp sign_in(user, password, conn) when is_map(user) do
    cond do
      Comeonin.Bcrypt.checkpw(password, user.encrypted_password) ->
        conn
          |> put_session(:current_user, user)
          |> put_flash(:info, "You are now signed in.")
          |> redirect(to: "/")
      true ->
        conn
         |> put_flash(:error, "Username or password are incorrect.")
         |> render "new.html", changeset: User.changeset(%User{})
    end
  end
end

web/views/blogs_view.ex
defmodule Blognix.BlogsView do
  use Blognix.Web, :view
end

web/views/error_view.ex
defmodule Blognix.ErrorView do
  use Blognix.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Blognix.LayoutView do
  use Blognix.Web, :view
end

web/views/page_view.ex
defmodule Blognix.PageView do
  use Blognix.Web, :view
end

web/views/registration_view.ex
defmodule Blognix.RegistrationView do
  use Blognix.Web, :view
end

web/views/session_view.ex
defmodule Blognix.SessionView do
  use Blognix.Web, :view
end

web/templates/blogs/new.html.eex
<h1>Create your blog</h1>
<%= form_for @changeset, blogs_path(@conn, :create), fn f -> %>
  <%= if f.errors != [] do %>
    <div class="alert alert-danger">
      <p>Oops, somethingwent wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Title</label>
    <%= text_input f, :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Description</label>
    <%= textarea f, :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Create Blog", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/blogs/show.html.eex
<h1><%= String.capitalize(@blog.title) %></h1>
<h3><%= @blog.description %></h3>

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blognix</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    </div>

    <div class="text-center">
      <h1>Blognix</h1>
      <%= if @conn.assigns[:current_user] do %>
        <%= @conn.assigns.current_user.username %>
        <%= link("Log Out", to: session_path(@conn, :delete)) %>
      <% end %>
    </div>

    <div class="container">
      <%= @inner %>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>require("web/static/js/app")</script>
  </body>
</html>

web/templates/session/new.html.eex
<h3>Login</h3>
<%= form_for @changeset, session_path(@conn, :create), fn f -> %>
  <%= if f.errors != [] do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Email</label>
    <%= text_input f, :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Password</label>
    <%= password_input f, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Login", class: "btn btn-primary" %>
    <%= link("Sign Up", to: registration_path(@conn, :new), class: "btn btn-success pull-right") %>
  </div>
<% end %>